# Generated by Django 4.2.7 on 2026-02-26 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renaloc', '0002_commune_created_at_commune_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Seuls les chiffres sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='departement',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Seuls les chiffres sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='quartiervillage',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Seuls les chiffres sont autorisés.')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Seuls les chiffres sont autorisés.')]),
        ),
    ]
