# Generated by Django 4.2.7 on 2026-02-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renaloc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementFormel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé')], max_length=20)),
                ('zone', models.CharField(choices=[('URBAINE', 'Urbaine'), ('RURALE', 'Rurale')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('dre', models.CharField(blank=True, max_length=100, verbose_name='DRE/FT/P')),
                ('ipde', models.CharField(blank=True, max_length=100, verbose_name='IPDE/FT/P')),
                ('date_autorisation', models.DateField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('type_etablissement', models.CharField(choices=[('LP', 'Lycée Professionnel'), ('LT', 'Lycée Technique'), ('LTE', 'Lycée Technologique'), ('LA', 'Lycée Agricole'), ('CFPT', 'CFPT'), ('CFPP', 'CFPP'), ('CMCAN', 'CMCAN'), ('EI', 'Ecole/Institut'), ('CET', 'CET'), ('CFM', 'CFM'), ('CPJ', 'CPJ'), ('EFAC', 'EFAC'), ('CFPT_AMA', 'CFPT AMA'), ('ENI', 'ENI'), ('CENTRE_MUSEE', 'Centre éducatif du musée national'), ('CFJA', 'CFJA'), ('CFMAA', 'CFMAA')], max_length=20)),
                ('cycle_base_1', models.BooleanField(default=False, verbose_name='Base 1 (CQP)')),
                ('cycle_base_2', models.BooleanField(default=False, verbose_name='Base 2 (CAP)')),
                ('cycle_moyen_1', models.BooleanField(default=False, verbose_name='Moyen 1 (BEP)')),
                ('cycle_moyen_2', models.BooleanField(default=False, verbose_name='Moyen 2 (BAC - BEPC+4 - BAC+1)')),
                ('regime', models.CharField(choices=[('INTERNAT', 'Internat'), ('EXTERNAT', 'Externat')], max_length=20)),
                ('internat_fonctionnel', models.BooleanField(blank=True, null=True)),
                ('patrimoine_foncier', models.CharField(blank=True, max_length=50)),
                ('ministere_tutelle', models.CharField(blank=True, max_length=100)),
                ('type_formation', models.CharField(blank=True, max_length=50)),
                ('dispositif_orientation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.commune')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.departement')),
                ('quartier_village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.quartiervillage')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.region')),
            ],
            options={
                'verbose_name': 'Établissement formel',
                'verbose_name_plural': 'Établissements formels',
            },
        ),
        migrations.CreateModel(
            name='FormateurFormel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('FONCTIONNAIRE', 'Fonctionnaire'), ('CONTRACTUEL', 'Contractuel'), ('ASCN', 'ASCN'), ('PERMANENT', 'Permanent'), ('VOLONTAIRE', 'Volontaire/Bénévole')], max_length=20)),
                ('nationalite', models.CharField(choices=[('NIGERIENNE', 'Nigérienne'), ('ETRANGERE', 'Étrangère')], max_length=20)),
                ('nom_prenom', models.CharField(max_length=200)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('annee_recrutement', models.IntegerField()),
                ('diplome_academique', models.CharField(blank=True, max_length=100)),
                ('diplome_professionnel', models.CharField(blank=True, max_length=100)),
                ('disciplines_enseignees', models.TextField()),
                ('volume_horaire_hebdo', models.IntegerField()),
                ('a_recu_renforcement', models.BooleanField(default=False)),
                ('a_ete_inspecte', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs', to='eftp_formel.etablissementformel')),
            ],
            options={
                'verbose_name': 'Formateur formel',
                'verbose_name_plural': 'Formateurs formels',
            },
        ),
        migrations.CreateModel(
            name='FiliereFormel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur', models.CharField(choices=[('PRIMAIRE', 'Secteur Primaire/Agricole'), ('SECONDAIRE', 'Secteur Secondaire/Industriel'), ('TERTIAIRE', 'Secteur Tertiaire/Service')], max_length=20)),
                ('nom_filiere', models.CharField(max_length=200)),
                ('diplome_prepare', models.CharField(max_length=200)),
                ('cycle', models.CharField(choices=[('BASE_1', 'Base 1 (CQP)'), ('BASE_2', 'Base 2 (CAP)'), ('MOYEN_1', 'Moyen 1 (BEP)'), ('MOYEN_2', 'Moyen 2 (BAC - BEPC+4 - BAC+1)')], max_length=20)),
                ('duree_formation', models.IntegerField(help_text='Durée en mois')),
                ('nb_groupes_pedagogiques', models.IntegerField(default=1)),
                ('heures_pratique_hebdo', models.IntegerField(default=0)),
                ('stage_obligatoire', models.BooleanField(default=False)),
                ('effectif_m', models.IntegerField(default=0)),
                ('effectif_f', models.IntegerField(default=0)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='eftp_formel.etablissementformel')),
            ],
            options={
                'verbose_name': 'Filière formelle',
                'verbose_name_plural': 'Filières formelles',
            },
        ),
        migrations.CreateModel(
            name='ApprenantFormel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('BASE_1', 'Base 1 (CQP)'), ('BASE_2', 'Base 2 (CAP)'), ('MOYEN_1', 'Moyen 1 (BEP)'), ('MOYEN_2', 'Moyen 2 (BAC - BEPC+4 - BAC+1)')], max_length=20)),
                ('annee_etude', models.CharField(choices=[('1ERE', '1ère année'), ('2EME', '2ème année'), ('3EME', '3ème année'), ('4EME', '4ème année')], max_length=10)),
                ('masculin', models.IntegerField(default=0)),
                ('feminin', models.IntegerField(default=0)),
                ('redoublants_m', models.IntegerField(default=0)),
                ('redoublants_f', models.IntegerField(default=0)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenants', to='eftp_formel.etablissementformel')),
            ],
            options={
                'verbose_name': 'Apprenant formel',
                'verbose_name_plural': 'Apprenants formels',
            },
        ),
    ]
