# Generated by Django 4.2.7 on 2026-02-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renaloc', '0003_alter_commune_code_alter_departement_code_and_more'),
        ('eftp_formel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissementformel',
            options={'ordering': ['code'], 'verbose_name': 'Établissement formel', 'verbose_name_plural': 'Établissements formels'},
        ),
        migrations.AddField(
            model_name='etablissementformel',
            name='sigle',
            field=models.CharField(blank=True, help_text='Ex: LP, LT, CFPT...', max_length=20, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.commune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='date_autorisation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'autorisation"),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'ouverture"),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='dispositif_orientation',
            field=models.BooleanField(default=False, verbose_name="Dispositif d'orientation"),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='internat_fonctionnel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Internat fonctionnel'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='ministere_tutelle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ministère de tutelle'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='nom',
            field=models.CharField(max_length=200, verbose_name="Nom de l'établissement"),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='patrimoine_foncier',
            field=models.CharField(blank=True, max_length=50, verbose_name='Patrimoine foncier'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='quartier_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='renaloc.quartiervillage', verbose_name='Quartier/Village'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='regime',
            field=models.CharField(choices=[('INTERNAT', 'Internat'), ('EXTERNAT', 'Externat')], max_length=20, verbose_name='Régime'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='statut',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé')], max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='type_etablissement',
            field=models.CharField(choices=[('LP', 'Lycée Professionnel'), ('LT', 'Lycée Technique'), ('LTE', 'Lycée Technologique'), ('LA', 'Lycée Agricole'), ('CFPT', 'CFPT'), ('CFPP', 'CFPP'), ('CMCAN', 'CMCAN'), ('EI', 'Ecole/Institut'), ('CET', 'CET'), ('CFM', 'CFM'), ('CPJ', 'CPJ'), ('EFAC', 'EFAC'), ('CFPT_AMA', 'CFPT AMA'), ('ENI', 'ENI'), ('CENTRE_MUSEE', 'Centre éducatif du musée national'), ('CFJA', 'CFJA'), ('CFMAA', 'CFMAA'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'établissement"),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='type_formation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Type de formation'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='etablissementformel',
            name='zone',
            field=models.CharField(choices=[('URBAINE', 'Urbaine'), ('RURALE', 'Rurale')], max_length=20, verbose_name='Zone'),
        ),
    ]
