# Generated by Django 4.2.7 on 2026-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eftp_formel', '0002_alter_etablissementformel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissementformel',
            name='sigle',
            field=models.CharField(blank=True, help_text='Ex: IAT, ENAM, LP, LT, CFPT...', max_length=20, verbose_name='Sigle'),
        ),
    ]
