# Generated by Django 4.2.7 on 2026-02-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('taille_fichier', models.BigIntegerField(default=0, help_text='Taille en octets')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('IN_PROGRESS', 'En cours')], default='IN_PROGRESS', max_length=20)),
                ('type_backup', models.CharField(choices=[('MANUAL', 'Manuelle'), ('AUTOMATIC', 'Automatique'), ('SCHEDULED', 'Planifiée')], default='MANUAL', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('chemin_fichier', models.CharField(max_length=500)),
                ('logs', models.TextField(blank=True, help_text='Logs détaillés de la sauvegarde')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de sauvegarde',
                'verbose_name_plural': 'Historiques des sauvegardes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RestoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_restauration', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('IN_PROGRESS', 'En cours')], default='IN_PROGRESS', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurations', to='core.backuphistory')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de restauration',
                'verbose_name_plural': 'Historiques des restaurations',
                'ordering': ['-date_restauration'],
            },
        ),
    ]
