# Generated by Django 4.2.7 on 2026-02-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renaloc', '0003_alter_commune_code_alter_departement_code_and_more'),
        ('eftp_non_formel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apprentinonformel',
            options={'ordering': ['secteur', 'duree_apprentissage'], 'verbose_name': 'Apprenti non formel', 'verbose_name_plural': 'Apprentis non formels'},
        ),
        migrations.AlterModelOptions(
            name='maitreartisan',
            options={'ordering': ['nom_prenom'], 'verbose_name': 'Maître artisan', 'verbose_name_plural': 'Maîtres artisans'},
        ),
        migrations.AlterModelOptions(
            name='metiernonformel',
            options={'ordering': ['secteur', 'nom_metier'], 'verbose_name': 'Métier non formel', 'verbose_name_plural': 'Métiers non formels'},
        ),
        migrations.AlterModelOptions(
            name='structurenonformelle',
            options={'ordering': ['code'], 'verbose_name': 'Structure non formelle', 'verbose_name_plural': 'Structures non formelles'},
        ),
        migrations.AddField(
            model_name='apprentinonformel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apprentinonformel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maitreartisan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='maitreartisan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='metiernonformel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='metiernonformel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='structurenonformelle',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='structurenonformelle',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='duree_apprentissage',
            field=models.CharField(choices=[('<=3', '≤ 3 mois'), ('4-9', '4 à 9 mois'), ('>9', '> 9 mois')], max_length=5, verbose_name="Durée d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='feminin',
            field=models.IntegerField(default=0, verbose_name='Féminin'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='jeunes_inscrits_f',
            field=models.IntegerField(default=0, verbose_name='Jeunes inscrits F'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='jeunes_inscrits_m',
            field=models.IntegerField(default=0, verbose_name='Jeunes inscrits M'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='masculin',
            field=models.IntegerField(default=0, verbose_name='Masculin'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='outilles_f',
            field=models.IntegerField(default=0, verbose_name='Outillés F'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='outilles_m',
            field=models.IntegerField(default=0, verbose_name='Outillés M'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='places_f',
            field=models.IntegerField(default=0, verbose_name='Placés F'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='places_m',
            field=models.IntegerField(default=0, verbose_name='Placés M'),
        ),
        migrations.AlterField(
            model_name='apprentinonformel',
            name='secteur',
            field=models.CharField(choices=[('PRIMAIRE', 'Secteur Primaire/Agricole'), ('SECONDAIRE', 'Secteur Secondaire/Industriel'), ('TERTIAIRE', 'Secteur Tertiaire/Service')], max_length=20, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='a_recu_suivi',
            field=models.BooleanField(default=False, verbose_name='A reçu un suivi technico-pédagogique'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='annee_certification',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de certification'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='dernier_certificat',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dernier certificat'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='formation_initiale',
            field=models.BooleanField(default=False, verbose_name='Formation initiale'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='grade',
            field=models.CharField(choices=[('MAITRE', 'Maître artisan'), ('FORMATEUR', 'Formateur')], max_length=20, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='nationalite',
            field=models.CharField(choices=[('NIGERIEN', 'Nigérien'), ('UEMOA', 'UEMOA'), ('AUTRE', 'Autre')], default='NIGERIEN', max_length=20, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='nb_formation_continue',
            field=models.IntegerField(default=0, verbose_name='Nombre de formations continues'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='niveau_certificat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Niveau du certificat'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='nom_prenom',
            field=models.CharField(max_length=200, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='qualification_certifiee',
            field=models.BooleanField(default=False, verbose_name='Qualification certifiée'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='maitreartisan',
            name='structure_certifiante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Structure certifiante'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='deplaces_f',
            field=models.IntegerField(default=0, verbose_name='Déplacés F'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='deplaces_m',
            field=models.IntegerField(default=0, verbose_name='Déplacés M'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='duree_apprentissage',
            field=models.CharField(choices=[('<=3', '≤ 3 mois'), ('4-9', '4 à 9 mois'), ('>9', '> 9 mois')], max_length=5, verbose_name="Durée d'apprentissage"),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='handicapes_f',
            field=models.IntegerField(default=0, verbose_name='Handicapés F'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='handicapes_m',
            field=models.IntegerField(default=0, verbose_name='Handicapés M'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='nom_metier',
            field=models.CharField(max_length=200, verbose_name='Nom du métier'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='refugies_f',
            field=models.IntegerField(default=0, verbose_name='Réfugiés F'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='refugies_m',
            field=models.IntegerField(default=0, verbose_name='Réfugiés M'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='retournes_f',
            field=models.IntegerField(default=0, verbose_name='Retournés F'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='retournes_m',
            field=models.IntegerField(default=0, verbose_name='Retournés M'),
        ),
        migrations.AlterField(
            model_name='metiernonformel',
            name='secteur',
            field=models.CharField(choices=[('PRIMAIRE', 'Secteur Primaire/Agricole'), ('SECONDAIRE', 'Secteur Secondaire/Industriel'), ('TERTIAIRE', 'Secteur Tertiaire/Service')], max_length=20, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_bibliotheque',
            field=models.BooleanField(default=False, verbose_name='Bibliothèque'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_boite_pharmacie',
            field=models.BooleanField(default=False, verbose_name='Boîte à pharmacie'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_cloture',
            field=models.BooleanField(default=False, verbose_name='Clôture'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_collecte_ordures',
            field=models.BooleanField(default=False, verbose_name='Collecte des ordures'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_connexion_internet',
            field=models.BooleanField(default=False, verbose_name='Connexion Internet'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_cour_recreation',
            field=models.BooleanField(default=False, verbose_name='Cour de récréation'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_depotoir',
            field=models.BooleanField(default=False, verbose_name='Dépotoir'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_document',
            field=models.BooleanField(default=False, verbose_name='Document administratif'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_electricite',
            field=models.BooleanField(default=False, verbose_name='Alimentation électrique'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_infirmerie',
            field=models.BooleanField(default=False, verbose_name='Infirmerie fonctionnelle'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_latrines',
            field=models.BooleanField(default=False, verbose_name='Latrines'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_lavage_mains',
            field=models.BooleanField(default=False, verbose_name='Dispositif lavage mains'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_paysage',
            field=models.BooleanField(default=False, verbose_name='Aménagement paysagé'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_point_eau',
            field=models.BooleanField(default=False, verbose_name="Point d'eau potable"),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_rampes_handicapes',
            field=models.BooleanField(default=False, verbose_name='Rampes pour handicapés'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='a_terrain_sport',
            field=models.BooleanField(default=False, verbose_name='Terrain de sport'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='acces_internet',
            field=models.JSONField(blank=True, default=list, verbose_name='Accès Internet'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='autre_type_precision',
            field=models.CharField(blank=True, max_length=200, verbose_name='Précision autre type'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.commune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='date_autorisation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'autorisation"),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='date_ouverture',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'ouverture"),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='delivre_attestation',
            field=models.BooleanField(default=False, verbose_name='Délivre des attestations'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='formation_payante',
            field=models.BooleanField(default=False, verbose_name='Formation payante'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='latrines_apprenants',
            field=models.IntegerField(default=0, verbose_name='Latrines pour apprenants'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='latrines_filles',
            field=models.IntegerField(default=0, verbose_name='Latrines pour filles'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='latrines_handicapes',
            field=models.IntegerField(default=0, verbose_name='Latrines pour handicapés'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='latrines_personnel',
            field=models.IntegerField(default=0, verbose_name='Latrines pour personnel'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='ministere_tutelle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ministère de tutelle'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='mode_paiement',
            field=models.JSONField(blank=True, default=list, verbose_name='Modes de paiement'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nb_formateurs_f',
            field=models.IntegerField(default=0, verbose_name='Formateurs F'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nb_formateurs_h',
            field=models.IntegerField(default=0, verbose_name='Formateurs H'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nb_maitres_artisans_f',
            field=models.IntegerField(default=0, verbose_name='Maîtres artisans F'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nb_maitres_artisans_h',
            field=models.IntegerField(default=0, verbose_name='Maîtres artisans H'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la structure'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nombre_depotoirs',
            field=models.IntegerField(default=0, verbose_name='Nombre de dépotoirs'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='nombre_latrines',
            field=models.IntegerField(default=0, verbose_name='Nombre total de latrines'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='quartier_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='renaloc.quartiervillage', verbose_name='Quartier/Village'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='reference_document',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence du document'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='regime',
            field=models.CharField(choices=[('INTERNAT', 'Internat'), ('EXTERNAT', 'Externat')], default='EXTERNAT', max_length=20, verbose_name='Régime'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renaloc.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='source_eau',
            field=models.CharField(blank=True, choices=[('ROBINET', 'Robinet'), ('AEP', 'AEP'), ('FORAGE', 'Forage'), ('PUITS', 'Puits cimenté')], max_length=20, verbose_name='Source eau'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='source_electricite',
            field=models.CharField(blank=True, choices=[('GROUPE', 'Groupe électrogène'), ('SOLAIRE', 'Panneau solaire'), ('RESEAU', 'Réseau électrique')], max_length=20, verbose_name='Source électricité'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='source_financement',
            field=models.JSONField(blank=True, default=list, verbose_name='Sources de financement'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='statut',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE', 'Privé')], max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='type_accompagnement',
            field=models.JSONField(blank=True, default=list, verbose_name="Types d'accompagnement"),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='type_connexion',
            field=models.CharField(blank=True, choices=[('ADSL', 'ADSL'), ('VSAT', 'VSAT'), ('MOBILE', 'Connexion mobile'), ('FIBRE', 'Fibre optique'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de connexion'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='type_document',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='type_structure',
            field=models.CharField(choices=[('SFMA', 'SFMA (SIFA)'), ('CFA', 'CFA'), ('ATELIER', 'Atelier'), ('SAA', 'SAA'), ('FOYER', 'Foyer'), ('GROUPEMENT', 'Groupement'), ('GARAGE', 'Garage'), ('COOPERATIVE', 'Coopérative/Association'), ('CABINET', 'Cabinet de formation'), ('PLATEFORME', "Plateforme d'orientation"), ('AUTRE', 'Autre structure')], max_length=20, verbose_name='Type de structure'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='structurenonformelle',
            name='zone',
            field=models.CharField(choices=[('URBAINE', 'Urbaine'), ('RURALE', 'Rurale')], max_length=20, verbose_name='Zone'),
        ),
    ]
